### ISSUE TITLE
App image problems

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#111]
I had to change the images of an app, so I uploaded a transparent image as iOS icon. However, the iOS icon was transparent. In another attempt the icon suddenly had a black background, same for the android icon. When I re-upload the iOS icon, the android icon does not change anymore.

GIG-M-CC should
- [x] Save the image with transparent background as Facebook icon (1024x1024)
- [x] Place a white background behind the image for the iOS icon (1024x1024)
- [x] Place a white background behind the image and add rounded corners for the Android icon (512x512)
_____
I would also add checkboxes to the Android/registration-logo/about-header images
- Android icon
  - [ ] Auto-generate from iOS icon
- Registration logo and about header:
  - [ ] Use homescreen header

This way we can just upload a new iOS icon and the Android/Facebook icons are auto-generated. Same for the homescreen header

**Comment by bart-at-mobicage** [comment]
@abom, can you verify if the scenario in this ticket works? You can skip checkboxes that I mentioned.

**Comment by abom** [comment]
@bart-at-mobicage The problems still there, i uploaded a transparent image many times, the first time it generated a black-background with corners images for iOS, android and splash screen. Sometimes, the iOS and splash screen are transparent, and android icon has a black background.

Besides the caching problem, i need to refresh to make sure those are the actual selected images.

**Comment by abom** [comment]
I think we don't need the check boxes to generate the images, current behavior is good, if something is not found, it will be generated.

**Comment by abom** [comment]
http://gitlab.mobicage.com/rogerthat/app-configurator/merge_requests/42

**Comment by lucasvanhalst** [comment]
For the checkboxes, the same can be achieved now by first deleting the images you want to be regenerated

**Comment by lucasvanhalst** [comment]
Deploying now
