### ISSUE TITLE
Don't allow special chars in custom translation keys

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#115]
Translation keys can only contain characters a-Z and underscore

Adding a [pattern] directive to the translation key input & showing an error message if necessary should be sufficient

**Comment by abom** [comment]
Was about to create an issue for that, while typing / and \ by mistake, it throws some errors because of the regex.

**Comment by abom** [comment]
Sorry, it's a different issue then, the typing was on navigation item dialog (while editing the text).
