### ISSUE TITLE
generate custom translation keys

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#118]
instead of having the user enter them, generate them on the client. Ensure no conflicts are possible with the existing sources and existing custom translations

**Comment by abom** [comment]
Then we should change the name to anything other than "Custom Translations", entering only a single term for "translation" is a bit confusing i think.

**Comment by lucasvanhalst** [comment]
Yeah let's just not do this
