### ISSUE TITLE
Remove save button at the bottom of appearance/sidebar

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#120]
... And instead save when closing the dialog of an individual item. Else the user has to press save 2 times and that's a little confusing.

**Comment by abom** [comment]
What about items order? it's saved instantly or after pressing "Save"?

**Comment by lucasvanhalst** [comment]
Hmm I see, let's debounce that call by a second to avoid spamming the server with requests
search for `.ofType(AppsActionTypes.UPDATE_SIDEBAR)` in apps.effect.ts
and add `.debounceTime(1000)` and add `import 'rxjs/add/operator/debounceTime';` to the imports at the top of the file, that should be enough.

Downside is that showing the error messages will also be slightly delayed now. Speaking of which, they are kinda broken #99

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/plugin-mobicage-control-center#14
