### ISSUE TITLE
Saving a QR template with wrong size gives "500 internal server error"

### ISSUE THREAD

**Issue by abom** [rogerthat-platform/plugin-rogerthat-control-center#123]
When saving the QR code image with wrong size, instead of showing an error message, it shows "500 internal server error".

I think we need to modify the rogerthat-backend api for adding QR template.

**Comment by abom** [comment]
Related #48.

**Comment by lucasvanhalst** [comment]
Waiting to merge this until rogerthat-platform/rogerthat-backend#194 is merged
