### ISSUE TITLE
ae-veda app does not have a GCM_SENDER_ID

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/plugin-rogerthat-control-center#150]

**Comment by lucasvanhalst** [comment]
Will be fixed by adding GCM_SENDER_ID to this dictionary https://github.com/rogerthat-platform/plugin-rogerthat-control-center/blob/c756c9b8c0f11f65c867279deb26a1b3ff6bb464/plugins/rogerthat_control_center/bizz/backends.py#L62
