### ISSUE TITLE
Sometimes images are not pushed

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/plugin-rogerthat-control-center#152]
1. i started a build and it gave an error that feature.jpg was missing
2. i uploaded an image (just started the build i did not publish)
2. build failed and said feature.jpg did not exists (no commit found in history)

**Comment by lucasvanhalst** [comment]
Fixed by 7dbae7164c367f05f4dd9fd0efbc5b4e2a92eb42
