### ISSUE TITLE
Download button not always disabled when build aborted/failed

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/plugin-rogerthat-control-center#153]
![screen shot 2017-06-20 at 10 06 41](https://user-images.githubusercontent.com/1122760/27322982-39c334f4-55a0-11e7-9c94-ddf850565d92.png)

**Comment by RubenMattan** [comment]
The apk was created successfully, however the publish failed => improve error message

**Comment by lucasvanhalst** [comment]
Do the above by checking if the download url is available but the status == errored
