### ISSUE TITLE
In the store listing tab, add the apple review notes

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#157]
Don't use the same apple review notes for all apps.

![app-review-info](https://user-images.githubusercontent.com/17762105/27429628-fe7c56ee-5745-11e7-9b22-22e7ad9253fa.png)

- [x] Under developer accounts, make it possible to create 'apple review notes' templates, next to the default one that is currently hard-coded.
- [x] Under the "Store Listing" tab, add a drop down to select the correct 'apple review notes'
- [x] Create custom review notes for the MobieTrain and OSA Terminal apps
- [x] Modify the deployment scripts in the apps repo

**Comment by lucasvanhalst** [comment]
Closed by 2177f8b7fcbb4c677503fa53f265c998d2d27909
