### ISSUE TITLE
Improve build checks explanations

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#158]
Improve the errors the build checks generate by adding: 
- [ ] A link to where the configuration is supposed to be entered
- [ ] A more detailed description

The goal is to make it easier for the user what exactly is wrong and how they can fix it, so that they don't have to come us to complain about it.

So the dialog should look something like this:
```
Please set or correct the following configurations and try again:
<a [routerlink]="...." target="_blank"><h4>Sidebar custom translations</h4></a>
<p>The sidebar item with action "<action goes here>" 
contains "Invalid translation text goes here" as text, which is not in the custom translations. 
Add it to the custom translations <a [routerlink]=...>here</a>
```
Repeat this template for every error.

So instead of just sending the names of each error like it is now, also send data related to that error so we can translate it

**Comment by abom** [comment]
Was about to do this before but didn't know how to show it properly.
The way you described it means that every error will be shown separately?

**Comment by lucasvanhalst** [comment]
Yeah I'd show them under each other

Not the prettiest solution but it'll work 😛

**Comment by abom** [comment]
Yes, maybe with a scrollable dialog it will pretty :laughing:

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/plugin-mobicage-control-center#12
