### ISSUE TITLE
Delete app

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#163]
Make it possible to delete an app.

Delete it on rogerthat first:
- Validate that it can be deleted (don't delete if there is a ServiceIdentity that has this app, return an error)
- Delete AppSetings, App
- Delete any other models that contain app_id in the key or have app_id as one of its properties
- Delete it from models that have app_ids property

Delete it on bob:
- Appmetadata
- Build
- App
- delete folder in apps repo

Also, when creating an app fails on appcfg, delete it on rogerthat (in the proxy handler)

**Comment by bart-at-mobicage** [comment]
Don't delete if there is ServiceIndentity that has this app. Show an error message then.

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/plugin-mobicage-control-center#24
