### ISSUE TITLE
Add 4 default screenshots 

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#164]
Add 4 default screenshots on top of the generated one city apps where the main_language is dutch for iOS apps.

After running snapshot (apps repo: Fastfile_template.rb line 107-118), copy these screenshots the the `SCREENSHOT_PATH`

**Comment by bart-at-mobicage** [comment]
The screenshots are in this zip: [appstore-screenshots.zip](https://github.com/rogerthat-platform/plugin-rogerthat-control-center/files/1114554/appstore-screenshots.zip)
