### ISSUE TITLE
can't add auto-connected service with long e-mail address

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#192]
I tried to add `service-4bf3bdf1-8628-491d-849b-698d7503c68a@rogerth.at` but it failed

![screen shot 2017-07-24 at 17 34 38](https://user-images.githubusercontent.com/17762105/28531243-81c69262-7096-11e7-9722-fa74ceafc494.png)

**Comment by lucasvanhalst** [comment]
Seems to be fixed
