### ISSUE TITLE
Ratings configuration

### ISSUE THREAD

**Issue by abom** [rogerthat-platform/plugin-rogerthat-control-center#194]
- For every Rogerthat backend, enable the backend editors/admins to configure service sectors.
- For every app:
- [x] Make it possible to enable/disable ratings
- [x] A configuration page where the user can select service sectors, and configure topics/questions related to every sector.

Every sector will have a set of topics, which will have only a single related question.

Sectors, topics and questions should be translatable.

Related: https://github.com/rogerthat-platform/rogerthat-backend/issues/241

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/plugin-mobicage-control-center#23
