### ISSUE TITLE
Generate default qr template

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#200]
When uploading a new app icon, check if there's a qr template for this app. If not, generate one using the app icon

**Comment by abom** [comment]
I think we will need to generate an image like this one
![qr-hand-only](https://user-images.githubusercontent.com/511438/32419024-198c0ed8-c27c-11e7-8e45-e4526ece4d13.png)

And i need the dimensions of the logo and the image without the logo.

**Comment by bart-at-mobicage** [comment]
logo size: 72x72
template image size: 348x343
