### ISSUE TITLE
remove_user_from_organization 500 Internal Server Error 

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#208]
I tried to changed permissions for Steven from `Viewer` to `Editor`. However, according to the logs it looks like the code tries to remove Steven from `gig-mobile.developeraccounts.mobicage.admins` instead of `gig-mobile.developeraccounts.mobicage.viewers`

![screen shot 2017-08-29 at 09 41 13](https://user-images.githubusercontent.com/17762105/29809905-36111dc8-8c9e-11e7-9e39-89814c8126d8.png)

![screen shot 2017-08-29 at 09 43 42](https://user-images.githubusercontent.com/17762105/29810047-acbdd7ea-8c9e-11e7-8fea-58d3d3159850.png)

![screen shot 2017-08-29 at 09 44 01](https://user-images.githubusercontent.com/17762105/29810050-afd3aa54-8c9e-11e7-861c-3bd100eb938c.png)

**Comment by lucasvanhalst** [comment]
Was a 500 from itsyou.online https://github.com/itsyouonline/identityserver/issues/587
