### ISSUE TITLE
App name isn't updated on rogerthat-server

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#210]
I recently changed the name of an app (Threefold --> ThreeFold), and the app model wasn't updated.

<img width="598" alt="screen shot 2017-08-31 at 11 49 54" src="https://user-images.githubusercontent.com/17762105/29917564-a212d61a-8e42-11e7-8892-a09179d5a54a.png">

![screen shot 2017-08-31 at 11 50 53](https://user-images.githubusercontent.com/17762105/29917594-bc5ee73e-8e42-11e7-946f-304fdd8b7955.png)

**Comment by lucasvanhalst** [comment]
Seems like this was fixed
