### ISSUE TITLE
Add TOS Url

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#217]

**Comment by RubenMattan** [comment]
They can already be found in 'Store Listing > Translations'

So what needs to be done is the following:
- Move to 'Store Listing > General Information' (Privacy policy should be same url for all languages)
- Save that url in build.yaml (doc['APP_CONSTANTS']['TERMS_OF_SERVICE_URL'])

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/plugin-mobicage-control-center#10
