### ISSUE TITLE
Automate creating developer account

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#233]
- [x] Only ask for email, password (from apple id), permission group
- [x] Prefill permission group with the part in front of the @ from the email
- [x] On the server, before creating the developer account, run the script which gets the iOS dev team /  iPhone developer / iPhone distribution / ... and use that information to create the developer account.

**Comment by bart-at-mobicage** [comment]
```
user = team['currentTeamMember']

name = team['name']
apple_developer_account = 'mobicage@gmail.com'
ios_dev_team = team['teamId']
iphone_developer= "%s %s (%s)" % (user['lastName'], user['firstName'], user['teamMemberId']
iphone_distribution = "%s (%s)" % (team['name'], team['teamId'])
```
