### ISSUE TITLE
Add a configuration for embedded apps under build settings

### ISSUE THREAD

**Issue by abom** [rogerthat-platform/plugin-rogerthat-control-center#257]
See https://github.com/rogerthat-platform/rogerthat-android-client/issues/333.

Also https://github.com/rogerthat-platform/rogerthat-backend/issues/416 is related.

Should we update it completely or just add the support for this property under build settings in build.yaml files?

**Comment by abom** [comment]
Also, need more info of the embedded apps list, is it a predefined list (e.g. rogerthat-payment...etc) or just any value can be added to it?

**Comment by lucasvanhalst** [comment]
You can wait a bit with this, we're making https://github.com/rogerthat-platform/rogerthat-backend/issues/433 atm which will make these embedded apps obsolete I think.

**Comment by lucasvanhalst** [comment]
Yeah I think so. When we implement https://github.com/rogerthat-platform/rogerthat-backend/issues/444 this feature (apps baked into the .apk) can be totally removed.
