### ISSUE TITLE
QR code template improvement

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#269]
https://gig-mobile-cc.appspot.com/apps/be-lanaken/assets/qr-code-templates
![image](https://user-images.githubusercontent.com/17762105/38678124-6eb36784-3e60-11e8-9106-d9a18ab80d93.png)

The auto-generated QR code template should have a white area behind the app icon. I suggest to remove the OCA logo from the image below and then use it to generate the app's QR template:
![image](https://user-images.githubusercontent.com/17762105/38678313-eb71aa6a-3e60-11e8-93a6-cf5635c45a16.png)

**Comment by abom** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/458
