### ISSUE TITLE
The generated iTunesArtwork.png shouldn't contain an alpha channel

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#273]
The iOS icon is generated from a transparent 1024x1024 FB icon. We should find a way to save the iTunesArtwork.png without alpha channel.

`[16:31:53]: ERROR ITMS-90717: "Invalid App Store Icon. The App Store Icon in the asset catalog in 'be-nazareth.app' can't be transparent nor contain an alpha channel."`

**Comment by abom** [comment]
http://gitlab.mobicage.com/rogerthat/app-configurator/merge_requests/59
