### ISSUE TITLE
Images cache

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#284]
After uploading new images it shows the old images. When refreshing, the new images our shown. When going away from the page and then back the old images where visible again.

New:
![image 2018-06-27 11 32 42](https://user-images.githubusercontent.com/17762105/41965817-cf38cd50-79fd-11e8-9088-364ed815bd5e.jpg)

Old:
![image 2018-06-27 11 32 48](https://user-images.githubusercontent.com/17762105/41965822-d2d5d28c-79fd-11e8-85d0-5eed0c0c0be7.jpg)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/plugin-mobicage-control-center#27
