### ISSUE TITLE
Validation error. items: [object Object],[object Object], ...

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#99]
![screen shot 2017-05-10 at 11 58 15](https://cloud.githubusercontent.com/assets/17762105/25893416/03f020f0-3578-11e7-93c5-fefc1b381d43.png)

{"status_code":400,"data":{"items":[{},{},{},{},{},{"non_field_errors":["Action 'None' cannot be collapsed"]},{},{},{},{},{},{},{},{}]},"error":"validation_error"}

**Comment by lucasvanhalst** [comment]
The error shouldn't have happened and that has been fixed, but the error message obviously needs work

**Comment by bart-at-mobicage** [comment]
Appeared again for new Alken app

`{"color":"000000","footer":true,"footer_alignment":"bottom","style":"news","items":[{"collapse":false,"color":null,"text":"News","action_type":null,"action":"news","icon":"fa-newspaper-o"},{"collapse":false,"color":null,"text":"Messages","action_type":null,"action":"messages","icon":"fa-envelope"},{"collapse":false,"color":null,"text":"Agenda","action_type":"click","action":"agenda","icon":"fa-book"},{"collapse":true,"color":null,"text":"Community Services","action_type":null,"action":"community_services","icon":"fa-university"},{"collapse":false,"color":null,"text":"Merchants","action_type":null,"action":"merchants","icon":"fa-user"},{"collapse":false,"color":null,"text":"Associations","action_type":null,"action":"associations","icon":"fa-users"},{"collapse":false,"color":null,"text":"Care","action_type":null,"action":"emergency_services","icon":"fa-medkit"},{"collapse":false,"color":null,"text":"Friends","action_type":null,"action":"friends","icon":"fa-smile-o"},{"collapse":false,"color":null,"text":"Scan","action_type":null,"action":"scan","icon":"fa-qrcode"},{"collapse":false,"color":null,"text":"Profile","action_type":null,"action":"profile","icon":"fa-user"},{"collapse":false,"color":null,"text":"Settings","action_type":null,"action":"settings","icon":"fa-wrench"}],"toolbar":{"items":[{"collapse":false,"color":null,"text":"Reserve","action_type":"action","action":"reserve1","icon":"fa-cutlery"},{"collapse":false,"color":null,"text":"Order","action_type":"action","action":"__sln__.order","icon":"fa-shopping-cart"},{"collapse":false,"color":null,"text":"Agenda","action_type":"action","action":"agenda","icon":"fa-calendar"},{"collapse":true,"color":null,"text":"QR code","action_type":null,"action":"qrcode","icon":"fa-credit-card"}]}}`

![screen shot 2017-05-12 at 17 00 10](https://cloud.githubusercontent.com/assets/17762105/26003932/65faeab0-3734-11e7-8b6a-6d6b1f0e8cb8.png)

**Comment by abom** [comment]
This problem happens because the validation error returned from the server side can be complex, its structure is not always flat, it may contain arrays instead of only {key: value}: 

For example:
```
{
   "items":[
      {
         "action":[
            "Dit veld mag niet leeg zijn."
         ]
      },
      {

      },
      {

      },
      {

      },
      {

      },
      {

      },
      {

      },
      {

      },
      {

      },
      {

      },
      {

      }
   ]
}
```

So, it's better to handle each individual type with a custom handler just like what @lucasvanhalst did in NavigationItemListComponent.getErrorMessage(), which shows validation error on its right place.

For now, i only show the error message if it's a string, otherwise a custom handler should be implemented.
